//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suscito.Modules.AT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ATStyleRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ATStyleRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suscito.Modules.AT.Resources.ATStyleRes", typeof(ATStyleRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preoccupied, Open Heart.
        /// </summary>
        internal static string BowlbyStyle_Anxious_AKA {
            get {
                return ResourceManager.GetString("BowlbyStyle.Anxious.AKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People with this style have higher levels of anxiety when they are alone. They value relationships highly, but often worry that their partner is not as invested as they are..
        /// </summary>
        internal static string BowlbyStyle_Anxious_Description {
            get {
                return ResourceManager.GetString("BowlbyStyle.Anxious.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.attachmentproject.com/blog/anxious-attachment.
        /// </summary>
        internal static string BowlbyStyle_Anxious_LearnMoreUrl {
            get {
                return ResourceManager.GetString("BowlbyStyle.Anxious.LearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anxious.
        /// </summary>
        internal static string BowlbyStyle_Anxious_Name {
            get {
                return ResourceManager.GetString("BowlbyStyle.Anxious.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissive Avoidant, DA, Rolling Stone.
        /// </summary>
        internal static string BowlbyStyle_Avoidant_AKA {
            get {
                return ResourceManager.GetString("BowlbyStyle.Avoidant.AKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People with this style often feel they don’t need relationship to feel complete. They are fiercely independent and are uncomfortable when others depend on them or seek their approval..
        /// </summary>
        internal static string BowlbyStyle_Avoidant_Description {
            get {
                return ResourceManager.GetString("BowlbyStyle.Avoidant.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.attachmentproject.com/blog/avoidant-attachment-style.
        /// </summary>
        internal static string BowlbyStyle_Avoidant_LearnMoreUrl {
            get {
                return ResourceManager.GetString("BowlbyStyle.Avoidant.LearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoidant.
        /// </summary>
        internal static string BowlbyStyle_Avoidant_Name {
            get {
                return ResourceManager.GetString("BowlbyStyle.Avoidant.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fearful Avoidant, FA, Spice of Lifer.
        /// </summary>
        internal static string BowlbyStyle_Disorganized_AKA {
            get {
                return ResourceManager.GetString("BowlbyStyle.Disorganized.AKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People with this style want intimacy and closeness but are also afraid of them. Relationships and their partner can trigger confusing feelings of both desire and fear..
        /// </summary>
        internal static string BowlbyStyle_Disorganized_Description {
            get {
                return ResourceManager.GetString("BowlbyStyle.Disorganized.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.attachmentproject.com/blog/disorganized-attachment.
        /// </summary>
        internal static string BowlbyStyle_Disorganized_LearnMoreUrl {
            get {
                return ResourceManager.GetString("BowlbyStyle.Disorganized.LearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disorganized.
        /// </summary>
        internal static string BowlbyStyle_Disorganized_Name {
            get {
                return ResourceManager.GetString("BowlbyStyle.Disorganized.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BowlbyStyle_Secure_AKA {
            get {
                return ResourceManager.GetString("BowlbyStyle.Secure.AKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People with this style are comfortable depending on their partners and letting their partners depend on them. They are comfortable with honesty and emotional intimacy..
        /// </summary>
        internal static string BowlbyStyle_Secure_Description {
            get {
                return ResourceManager.GetString("BowlbyStyle.Secure.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.attachmentproject.com/blog/secure-attachment.
        /// </summary>
        internal static string BowlbyStyle_Secure_LearnMoreUrl {
            get {
                return ResourceManager.GetString("BowlbyStyle.Secure.LearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        internal static string BowlbyStyle_Secure_Name {
            get {
                return ResourceManager.GetString("BowlbyStyle.Secure.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BowlbyStyle_Unknown_AKA {
            get {
                return ResourceManager.GetString("BowlbyStyle.Unknown.AKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BowlbyStyle_Unknown_Description {
            get {
                return ResourceManager.GetString("BowlbyStyle.Unknown.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.attachmentproject.com/attachment-theory.
        /// </summary>
        internal static string BowlbyStyle_Unknown_LearnMoreUrl {
            get {
                return ResourceManager.GetString("BowlbyStyle.Unknown.LearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string BowlbyStyle_Unknown_Name {
            get {
                return ResourceManager.GetString("BowlbyStyle.Unknown.Name", resourceCulture);
            }
        }
    }
}
